name: Deploy WASM

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

env:
  RUST_BACKTRACE: 1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f

      - name: Install npm
        uses: actions/setup-node@v3
        with:
          node_version: 18

      - name: Build Kobold WASM module
        run: wasm-pack build wasm/lib

      - name: Install and build web interface
        run: |
          cd wasm/www
          npm ci
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
